services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Caretaker\Caretaker\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Caretaker\Caretaker\Controller\AdminModuleController:
    tags: ['backend.controller']
