services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Caretaker\Caretaker\:
    resource: '../Classes/*'
    exclude: '../Classes/Entity/*'

  Caretaker\Caretaker\Command\RunTestCommand:
    tags:
      - name: console.command
        command: 'caretaker:runtest'
        description: 'This command runs tests for a given node id.'
